<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShulkerRDK.Shared\ShulkerRDK.Shared.csproj">
          <Private>false</Private>
          <ExcludeAssets>runtime</ExcludeAssets>
      </ProjectReference>
      <ProjectReference Include="..\submodules\Trident.Net\src\TridentCore.Abstractions\TridentCore.Abstractions.csproj" />
      <ProjectReference Include="..\submodules\Trident.Net\src\TridentCore.Core\TridentCore.Core.csproj" />
      <ProjectReference Include="..\submodules\Trident.Net\src\TridentCore.Purl\TridentCore.Purl.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
    </ItemGroup>

</Project>
